galaxy_info:
  author: Serhio
  description: centos configuration role
  company: FBS
  license: BSD
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags: [centos, base, system, locale, hostname, timezone, epel]
dependencies: []
