---
all:
  children:
    puppet:
      children:
        puppet_master:
          hosts:
            pmstr.dev.lab: {}
        puppet_node:
          hosts:
            node-01.dev.lab: {}
            node-02.dev.lab: {}
  vars:
    ansible_user: deploy
    ansible_port: 22
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
